services:
  backend-cpu:
    build:
      context: ./backend
      args:
        ENABLE_GPU: 0
    env_file: [.env.production]
    environment:
      ASGI_WORKERS: ${ASGI_WORKERS:-4}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - insightface_models:/root/.insightface

  worker-cpu:
    build:
      context: ./worker
      args:
        ENABLE_GPU: 0
    env_file: [.env.production]
    volumes:
      - insightface_models:/root/.insightface

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-/api}
    ports:
      - "3000:80"

  nginx:
    build: ./nginx
    depends_on:
      - frontend
      - backend-cpu
    ports:
      - "80:80"
    environment:
      NGINX_MAX_BODY: ${NGINX_MAX_BODY:-50m}

volumes:
  insightface_models:
